Repository elementary/calculator, pull requests merged in 2021-07, with the labels that each got.

#184 Release 1.6.2
  data/io.elementary.calculator.appdata.xml.in
  data/screenshot-extended@2x.png
  data/screenshot@2x.png
  io.elementary.calculator.yml
  meson.build
Labels: Release

#185 Merge Action: Set branch to daily
  .github/workflows/merge.yml
Labels: Bitesize

#187 LINGUAS: Sort and add Panjab
  po/LINGUAS
  po/extra/LINGUAS
Labels: Bitesize, i18n

#143 Add Memory Functions (MS, MR, M+, M- and MC) and Grand Total to extended functionalities
  src/MainWindow.vala
Labels: Needs Copy, Needs Design
